config/routes.rb
Rails.application.routes.draw do
  root                            to: 'welcome#index'
  get '/auth/automatic',          as: :login
  get '/auth/automatic/callback', to: "sessions#create"
  get '/logout',                  to: "sessions#destroy"
  get '/dashboard',               to: "dashboards#index"
  resources :trips,               only: [:index, :show]
  resources :vehicles,            only: [:index, :show]
  get '/current',                 to: 'users#current'
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :vehicle

  def self.create_from_api(data)
    data.each do |trip|
      if trip
        vehicle_id = Vehicle.find_by(url: trip[:vehicle]).id
        unless found = Trip.find_by(tid: trip[:id])
          Trip.create( { vehicle_id:            vehicle_id,
                         average_kmpl:          trip[:average_kmpl],
                         vehicle_url:           trip[:url],
                         started_at:            trip[:started_at],
                         start_timezone:        trip[:start_timezone],
                         average_from_epa_kmpl: trip[:average_from_epa_kmpl],
                         fuel_cost_usd:         trip[:fuel_cost_usd],
                         fuel_volume_l:         trip[:fuel_volume_l],
                         tid:                   trip[:id],
                         distance_m:            trip[:distance_m],
                         ended_at:              trip[:ended_at],
                         end_timezone:          trip[:end_timezone],
                         user_url:              trip[:user],
                         idling_time_s:         trip[:idling_time_s],
                         duration_s:            trip[:duration_s],
                         path:                  trip[:path],
                         start_address:         trip[:start_address][:name],
                         end_address:           trip[:end_address][:name],
                         start_lon:             trip[:start_location][:lon],
                         start_lat:             trip[:start_location][:lat],
                         end_lon:               trip[:end_location][:lon],
                         end_lat:               trip[:end_location][:lat] } )
        end
      end
    end
  end

  def self.average_cost
    average(:fuel_cost_usd).round(2)
  end

  def self.average_mpg
    (average(:average_kmpl) * 2.35214583).round(2)
  end
end

app/models/trip_service.rb
class TripService
  attr_reader :user

  def initialize(user)
    @user = user
  end

  def service
    AutomaticService.new(user.oauth_access_token)
  end

  def all
    trips.map { |trip| build_object(trip) }
  end

  def trips
    @trips ||= service.trips
  end

  def save_trips
    Trip.create_from_api(trips)
  end

  private

    def build_object(data)
      OpenStruct.new(data)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vehicles
  has_many :trips, through: :vehicles

  def self.from_omniauth(auth_info)
    where(uid: auth_info["info"]["id"]).first_or_create do |new_user|
      new_user.uid                = auth_info["info"]["id"]
      new_user.first_name         = auth_info["info"]["first_name"]
      new_user.last_name          = auth_info["info"]["last_name"]
      new_user.email              = auth_info["info"]["email"]
      new_user.oauth_access_token = auth_info["credentials"]["token"]
      new_user.token_expires_at   = auth_info["credentials"]["expires_at"]
    end
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
  has_many :trips

  def self.create_from_api(data, user)
    data.each do |vehicle|
      unless veh = Vehicle.find_by(vid: vehicle[:id])
        Vehicle.create!( { url:        vehicle[:url],
                           vid:        vehicle[:id],
                           vin:        vehicle[:vin],
                           make:       vehicle[:make],
                           model:      vehicle[:model],
                           submodel:   vehicle[:submodel],
                           year:       vehicle[:year],
                           fuel_grade: vehicle[:fuel_grade],
                           user_id:    user.id } )
      end
    end
  end
end

app/models/vehicle_service.rb
class VehicleService
  attr_reader :user

  def initialize(user)
    @user = user
  end

  def service
    AutomaticService.new(user.oauth_access_token)
  end

  def all
    vehicles.map { |vehicle| build_object(vehicle) }
  end

  def vehicles
    @vehicles ||= service.vehicles
  end

  def save_vehicles
    Vehicle.create_from_api(vehicles, user)
  end

  private

    def build_object(data)
      OpenStruct.new(data)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    VehicleSaveWorker.perform_async(current_user.id)
    TripSaveWorker.perform_async(current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to dashboard_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
    end
    redirect_to root_path
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = current_user.trips.order(started_at: :desc)
    @ave_cost = Trip.average_cost
    @ave_mpg = Trip.average_mpg
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def current
    render json: current_user
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :require_login

  def index
    @vehicles = current_user.vehicles
  end

  def show
    vehicle = Vehicle.find(params[:id])
    @vehicle = vehicle if vehicle.user_id == current_user.id
  end

  private

    def require_login
      redirect_to login_path unless current_user
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :redirect_if_logged_in

  def index
  end

  private

    def redirect_if_logged_in
      if current_user
        redirect_to dashboard_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Autolizer"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboards/index.html.erb
<%= provide(:title, "Dashboard") %>
<% cache("background") do %>
  <%= render partial: 'layouts/nav' %>
  <body class="lykan-background" />

  <div class="header-buffer ui vertical segment h-350"></div>
<% end %>

<%= render partial: 'shared/vehicle_stats' %>

<div class="header-buffer ui vertical segment h-350"></div>

<%= render partial: 'shared/last_trip_stats' %>

<div class="header-buffer ui vertical segment h-350"></div>

<%= render partial: 'shared/driver_stats' %>

<div class="header-buffer ui vertical segment h-350"></div>

<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<div class="ui fixed inverted vertical footer segment footer-stripe">
  <div class="ui center aligned container">
    <img src="<%= asset_path('A-logo-sm-bw.png') %>" class="ui centered mini image" id="footer-logo">
    <small>
      2016 Autolizer
    </small>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="ui top fixed inverted menu" id="top-nav">
  <div class="item">
    <a href="<%= dashboard_path %>" class="nav-item item">
      <h4 class="white">DASHBOARD</h4>
    </a>
  </div>
  <div class="item">
    <a href="<%= vehicles_path %>" class="nav-item item">
      <h4 class="white">VEHICLES</h4>
    </a>
  </div>
  <div class="item">
    <a href="<%= trips_path %>" class="nav-item item">
      <h4 class="white">TRIPS</h4>
    </a>
  </div>
  <div class="ui container nav-item">
    <img src="<%= asset_path('A-logo.png') %>" id="nav-logo">
  </div>
  <div class="float right item">
    <a href="<%= logout_path %>" class="nav-item item">
      <h4 class="white">LOGOUT</h4>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/shared/_driver_stats.html.erb
<div class="ui center aligned container vehicle-stat-header">
  <h1 class="white">Driver</h1>
</div>

<div class="feature alternate ui stripe vertical segment">
  <div class="ui three column center aligned divided relaxed stackable stat-row grid container">
    <div class="row">
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="last-trip-hard-brakes">
          </div>
          <div class="label">
            Hard Brakes
          </div>
        </div>
      </div>
      <div class="column mid-stat">
        <div class="ui inverted statistic">
          <div class="value" id="last-trip-hard-accels">
          </div>
          <div class="label">
            Hard Accels
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="last-trip-duration-70">
          </div>
          <div class="label">
            Seconds over 70 MPH
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_last_trip_stats.html.erb
<div class="ui center aligned container vehicle-stat-header">
  <h1 class="white">Last Trip</h1>
</div>

<div class="feature alternate ui stripe vertical segment">
  <div class="ui three column center aligned divided relaxed stackable stat-row grid container">
    <div class="row">
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="last-trip-distance">
          </div>
          <div class="label">
            Distance Miles
          </div>
        </div>
      </div>
      <div class="column mid-stat">
        <div class="ui inverted statistic">
          <div class="value" id="last-trip-duration">
          </div>
          <div class="label">
            Minutes
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="last-trip-cost">
          </div>
          <div class="label">
            Fuel Cost USD
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
  <div class="ui center aligned divided relaxed stackable stat-bottom grid container">
    <div class="row">
      <div class="ui inverted relaxed divided list">
        <div class="item">
          <i class="large inverted marker middle aligned icon"></i>
          <div class="content trip-summary">
            <p class="header">Start Location</p>
            <div class="description" id="last-trip-start">
            </div>
          </div>
        </div>
        <div class="item">
          <i class="large inverted marker middle aligned icon"></i>
          <div class="content trip-summary">
            <p class="header">End Location</p>
            <div class="description" id="last-trip-end">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_trip_table_row.html.erb
<tr>
  <td>
    <strong>Start: </strong><%= @trip.started_at.strftime("%m/%d/%Y at %I:%M%p") %><br>
    <strong>End: </strong><%= @trip.ended_at.strftime("%m/%d/%Y at %I:%M%p") %>
  </td>
  <td>
    <strong>Start: </strong><%= @trip.start_address %><br>
    <strong>End: </strong><%= @trip.end_address %>
  </td>
  <td><%= (@trip.duration_s / 60).round %></td>
  <td><%= (@trip.distance_m * 0.000621371).round(2) %></td>
  <td>$ <%= @trip.fuel_cost_usd %></td>
  <td><%= @trip.fuel_cost_usd %></td>
  <td><%= (@trip.average_kmpl * 2.35214583).round(2) %></td>
</tr>

app/views/shared/_vehicle_overview.html.erb
<div class="ui center aligned container vehicle-stat-header">
  <h1 class="white"><%= @vehicle.year %> <%= @vehicle.model %></h1>
</div>

<div class="feature alternate ui stripe vertical segment" id="feature-stripe">
  <div class="ui three column center aligned divided relaxed stackable stat-row grid container">
    <div class="row">
      <div class="ui text container">
        <h2>VIN: <%= @vehicle.vin.upcase %> / Submodel: <%= @vehicle.submodel %></h2>
        <a href="<%= vehicle_path(@vehicle) %>">
          <button class="ui button">Details</button>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_vehicle_stats.html.erb
<div class="ui center aligned container vehicle-stat-header">
  <h1 class="white" id="vehicle-title">
  </h1>
</div>

<div class="feature alternate ui stripe vertical segment">
  <div class="ui three column center aligned divided relaxed stackable stat-row grid container">
    <div class="row">
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="last-trip-fuel-economy">
          </div>
          <div class="label">
            Current MPG
          </div>
        </div>
      </div>
      <div class="column mid-stat">
        <div class="ui inverted statistic">
          <div class="value" id="vehicle-fuel-percent">
          </div>
          <div class="label">
            Current Fuel Level
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="vehicle-dtc-count">
          </div>
          <div class="label">
            Engine Trouble Codes
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<%= provide(:title, "Trips") %>
<%= render partial: 'layouts/nav' %>
<body class="trips" />

<div class="header-buffer ui vertical segment h-350"></div>
<div class="ui center aligned container vehicle-stat-header">
  <h1 class="white">All Trips</h1>
</div>

<div class="feature alternate ui stripe vertical segment">
  <div class="ui three column center aligned divided relaxed stackable stat-row grid container">
    <div class="row">
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="average-mpg">
            <%= @ave_mpg %>
          </div>
          <div class="label">
            Average MPG / Trip
          </div>
        </div>
      </div>
      <div class="column mid-stat">
        <div class="ui inverted statistic">
          <div class="value" id="average-fuel-cost-usd">
            $ <%= @ave_cost %>
          </div>
          <div class="label">
            Average Fuel Cost USD / Trip
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui inverted statistic">
          <div class="value" id="total-trips">
            <%= @trips.count %>
          </div>
          <div class="label">
            Trips
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

<div class="header-buffer ui vertical segment h-350"></div>
<div class="ui center aligned container vehicle-stat-header">
  <h1 class="white">Trip Details</h1>
</div>

<div class="ui container">
  <table class="ui celled table" id="trips-table">
    <thead>
      <tr>
      <th>Date / Time</th>
      <th>Locations</th>
      <th>Minutes</th>
      <th>Miles</th>
      <th>Cost USD</th>
      <th>Fuel(L)</th>
      <th>MPG</th>
      </tr>
    </thead>
    <tbody>
      <% @trips.each do |trip|  %>
        <% @trip = trip %>
        <%= render 'shared/trip_table_row', {locals: @trip} %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="header-buffer ui vertical segment h-250"></div>
<%= render 'layouts/footer' %>

app/views/trips/show.html.erb
<h1>Trips#show</h1>
<p>Find me in app/views/trips/show.html.erb</p>

app/views/users/current.html.erb
<h1>Users#current</h1>
<p>Find me in app/views/users/current.html.erb</p>

app/views/vehicles/index.html.erb
<%= provide(:title, "Vehicles") %>
<%= render partial: 'layouts/nav' %>
<body class="lykan-2-bw" />

<div class="header-buffer ui vertical segment h-350"></div>

<% @vehicles.each do |vehicle| %>
  <div class="ui vertical stripe segment" id="vehicles-stripe">
    <% @vehicle = vehicle %>
    <%= render 'shared/vehicle_overview', {locals: @vehicle} %>
  </div>
    <div class="header-buffer ui vertical segment h-300"></div>
<% end %>

<%= render 'layouts/footer' %>

app/views/vehicles/show.html.erb
<%= provide(:title, @vehicle.model) %>
<%= render partial: 'layouts/nav' %>
<body class="<%= controller_name %> <%= action_name %> lykan-3" />

<div class="header-buffer ui vertical segment h-250"></div>

<div class="ui center aligned container vehicle-stat-header">
  <h1 class="white" id="vin"><%= @vehicle.vin %></h1>
</div>

<div class="ui container" id="tab-form-container">
  <div class="ui top attached secondary pointing menu">
    <div class="active item" id="specs-tab">VEHICLE SPECS</div>
    <div class="item" id="maint-tab">MAINTENANCE ITEMS</div>
  </div>
  <div class="ui bottom attached active tab segment" id="specs-list">
  </div>
  <div class="ui bottom attached tab segment" id="maint-list">
  </div>
</div>

<%= render partial: 'layouts/footer' %>

app/views/welcome/index.html.erb
<%= provide(:title, "Login") %>
<% cache("background-logo") do %>
  <body class="login-background" />

  <div class="ui middle aligned center aligned grid" id="login-contain">
    <div class="column m-width-450 clear">
      <div class="ui container m-width-450">
        <img src="<%= asset_path('A-logo.png') %>" id="login-logo">
      </div>
      <div class="ui container m-width-450">
        <h1 class="white product-title">
          Autolizer
        </h1>
<% end %>

    <% if current_user %>
      <h1 class="white">Welcome, <%= current_user.first_name %></h1>
      <div class="ui container">
        <a href="<%= logout_path %>">
          <button class="ui fluid large inverted button">Logout</button>
        </a>
      </div>
    <% else %>
      <a href="<%= login_path %>" id="automatic-button">
        <img src="<%= asset_path('auth_automatic-login-hover-sm.svg') %>" id="log-in-button" />
      </a>
    <% end %>

  </div>
</div>